name: PR to Discord

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1439028156391755869/EohlujS0sudaAtj6krL_tDaJEHoZ8XWoiSghO6fTT-Hn55bpTm59H9OXPaQ3HuY46WJH"
          DISCORD_SENDER: "GitHub PR Bot"
        with:
          args: |
            **New Pull Request Created!** 
            ## ${{ github.event.pull_request.title }}
            ### ${{ github.event.pull_request.description }}
            ${{ github.event.pull_request.user.login }}, ${{ github.head_ref || github.ref_name }}
            
            ***Link: ${{ github.event.pull_request.html_url }}***